spring:
  data:
    mongodb:
      uri: mongodb://sanity:wordpass@localhost:27017/auth?authSource=admin
      uuid-representation: standard
  jackson:
    date-format: 'dd-MM-yyyy'
app:
  security:
    jwtSecret: "superSecretCode"
    jwtExpiration: 300000

